workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
- test

unit-test:
  image: maven:3.8.5-openjdk-17
  stage: test
  script:
    - mvn clean test
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml

coverage-report:
  dependencies: ["unit-test"]
  needs: ["unit-test"]
  stage: test
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    - java_src=$(find $(pwd) -type d -regex ".*src/main/kotlin" -exec echo {} \;)
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml ${java_src} > cobertura.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml